// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiTj7qNScy1XxDF-SitVBfL_HGm_SBr08',
    appId: '1:28461434716:web:fcf78104a482fb24362399',
    messagingSenderId: '28461434716',
    projectId: 'orienteering-858bc',
    authDomain: 'orienteering-858bc.firebaseapp.com',
    storageBucket: 'orienteering-858bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuHy8JYiqdK0yz7slC0Y4FU7kW9fZSfcA',
    appId: '1:28461434716:android:6c606a1a90715660362399',
    messagingSenderId: '28461434716',
    projectId: 'orienteering-858bc',
    storageBucket: 'orienteering-858bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJTxUnwq3wHwPFXAh1vm_xaY_hUQZkvLA',
    appId: '1:28461434716:ios:ddab15ae02732bb7362399',
    messagingSenderId: '28461434716',
    projectId: 'orienteering-858bc',
    storageBucket: 'orienteering-858bc.appspot.com',
    androidClientId: '28461434716-e1haiuba2tdaskpaoh05ppt3i102uoi0.apps.googleusercontent.com',
    iosClientId: '28461434716-5o506buoqqled1k0hvu18ot808831nds.apps.googleusercontent.com',
    iosBundleId: 'com.example.orienteering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJTxUnwq3wHwPFXAh1vm_xaY_hUQZkvLA',
    appId: '1:28461434716:ios:ddab15ae02732bb7362399',
    messagingSenderId: '28461434716',
    projectId: 'orienteering-858bc',
    storageBucket: 'orienteering-858bc.appspot.com',
    androidClientId: '28461434716-e1haiuba2tdaskpaoh05ppt3i102uoi0.apps.googleusercontent.com',
    iosClientId: '28461434716-5o506buoqqled1k0hvu18ot808831nds.apps.googleusercontent.com',
    iosBundleId: 'com.example.orienteering',
  );
}
